### ISSUE TITLE
Actions of the template not working if deploying in another region

### ISSUE THREAD

**Issue by benoit74** [gilt/cloudformation-helpers#1]
All actions of the create_cloudformation template that deploy a Lambda function are relying on the bucket "com.gilt.public.backoffice". Unfortunately, CloudFormation does not achieve to create these lambda functions.
It fails with the usual code "Permanently redirect ..." indicated that you try to access a s3 bucket not located in the same region as yours.
I downloaded the "cloudformation-helpers.zip" file, hosted it in a bucket in the right region, modified the template to point to my bucket and ... it works !
However, I don't know how to fix this easily. Maybe just some documentation on the README ...

But in the end : thank you very much for sharing all this code !

**Comment by benoit74** [comment]
Nota : I am deploying in eu-west-1, in which region is the bucket "com.gilt.public.backoffice" ?

**Comment by rlmartin** [comment]
Ok, thanks for the note. I've only ever tried deploying this in us-east-1. Either I need to created the same bucket in all regions, or I need to tweak the permissions on that bucket. I'll take a look.

**Comment by rlmartin** [comment]
I figured out the solution for this: I need one bucket for each region and can add a chain of cross-region replications to duplicate the file so it's available in all regions. This will also require a small change to the CloudFormation template; I'll comment back here when this is done.

**Comment by benoit74** [comment]
Nice ! Looking forward for the proper way to do this in the CloudFormation template.
